car_voice:
  output_wav_path: "D:/UserFiles/文件/研究生/工作项目/机器人框架v2/car_voice/output.wav"
  init_wav_path: 'D:/UserFiles/文件/研究生/工作项目/机器人框架v2/car_voice/init.wav'
  change_wav_path: 'D:/UserFiles/文件/研究生/工作项目/机器人框架v2/car_voice/change.wav'
  mic_name: 'UACDemoV1.0: USB Audio (hw:2,0)'
  threshold: 2500
  baidu_API_KEY: 'UwS3sG8nwyderc7plFV1fKhP'
  baidu_SECRET_KEY: 'ihnzCIhHIWndQmfryCFmVryqqilRIzEE'

car_knowledge:
  item_loc: {"杯子": "cup", "茶包": "chabao", "书": "book", "饮水机": "water", "我": "hand", "托盘": "tuopan"}
  locations: [{"name": "厨房", "location": "{'x': -1.356573771429246, 'y': 4.999944688176971, 'yaw': 0.7946730148562868, 'z': 0.0}"},
                 {"name": "卧室", "location": "{'x': -0.2218969712949318, 'y': -0.2515860317008285, 'yaw': -0.02445899149751707, 'z': 0.0}"},
                 {"name": "客厅", "location": "{'x': -1.170713179748654, 'y': 0.04374214671541992, 'yaw': -2.255652161020206, 'z': 0.0}"},
                 {"name": "办公室", "location": "{'x': 0.5901472270676184, 'y': 2.874371793727706, 'yaw': 1.185127366482732, 'z': 0.0}"}]
  HanLP_auth: "MzIxN0BiYnMuaGFubHAuY29tOkI0V0J3WE9CQVVyME1WMTg="
  OpenAI_API_Key: "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"
  arm_host: '192.168.3.36'
  car_host: '192.168.3.50'
  computer_host: '192.168.3.16'